# Site settings
title: You Link Blog
email: 18675559035@163.com
description: > # Study notes, resource sharing, practical projects, living with the mind. Program 
baseurl: "" # the subpath of your site, e.g. /blog/
betaurl: "http://beta.ulink-el.com"
url: "http://ulink-el.com" # the base hostname & protocol for your site
twitter_username: TINE4359
github_username:  Ja50n
weibo_username: TINE59

# Build settings
markdown: kramdown
# highlighter: rouge
excerpt_separator: <!--more-->
duoshuo_shortname:  Ja50n
paginate: 5
paginate_path: "page:num"
plugins: [jekyll-paginate]

port: 5000
